### ISSUE TITLE
Full-screen mode improvement

### ISSUE THREAD

**Issue by ghost** [lestcape/Configurable-Menu#36]
Right now the way the full-screen mode works is that it takes the boxpointer/popupmenu image and stretches is it.This is working pretty well, but it isn´t perfect.
If the popup-menu image has a border radius, then it will be seen when in fullscreen.
![secondary_001](https://f.cloud.github.com/assets/5655339/2428182/e1811538-ac31-11e3-9dca-faf8b1cefc88.png)

Also, when in full-screen, I would be able to get rid of any borders around the menu to make it look better!
![secondary_003](https://f.cloud.github.com/assets/5655339/2428198/1cacbcce-ac33-11e3-98ec-a8fae748c937.png)

Is it possible to set it up so that the menu first looks for a different/specific image(with a selector like ".full-screen-background"), and if it doesn´t find it, then it resorts to the previous method?
This way a theme could optimize the look of the fullscreen mode!

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
