### ISSUE TITLE
High Memory Allocation

### ISSUE THREAD

**Issue by megax** [lestcape/Configurable-Menu#58]
Hello,

When i navigate between categories and i will go thorugh once from the top to bottom then it allocates much ram. Though when i close the menu it gets freed.
For example i can easly allocate 10% of my RAM (4GB) in half a minute.
Also even from mouse moving in a less Cinnamon menu memory allocations still gets pretty high (the value is less here, less than ~1%).

Anybody has this issue?
(Archlinux, wm: Cinnamon 2.2.8, Configurable-Menu config: https://github.com/megax/dotfiles/blob/master/.cinnamon/configs/configurableMenu%40lestcape/configurableMenu%40lestcape.json)

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
