### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by sergioad** [lestcape/Configurable-Menu#68]
Hello @lestcape I have two suggestions for you

1.- add the posibility to save the current config of earch configurable menu style on a specific folder on the .config folder to be able to rescue or restablish the config in case of deleting the applet or some problem

2.- add a yaourt pkgbuild, the name must be cinnamon-applet-configurablemenu-git to install the applet via AUR and always get the newer updates from git

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
