### ISSUE TITLE
Tiles support for configurable menu? Win 8.1 like  menu?

### ISSUE THREAD

**Issue by bluedxca93** [lestcape/Configurable-Menu#69]
Hi,

is it possible to add a simple menu container which contains facorites, if you click on an specifed bitmap, the categories menu opens at the same place with an back arrow. If you click on the categorie tab you see then the applications . 
if you click on  back arrow  you see the favorites again. 

Same for recently used. 
If that is to complicated then the classical menu style, But

 More  important is for me at the moment  the possibility to place at bitmaps  ( normal,hovered,) that are placed right to the menu and the icon preview from applications centered on top and which positons can be changed in an human readable file ?.

On gnomenu there were the possibiltie to have bitmaps in the menu an dwhen you clicked on them they`ve done an action. Is this functionality possible on cinnamon?.
Perhaps someone has time to developp something like this....

regards bluedxca93

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
