### ISSUE TITLE
Sugerencias y Felicitaciones

### ISSUE THREAD

**Issue by nosferatux** [lestcape/Configurable-Menu#72]
Saludos cordiales:

Primero que nada mis felicitaciones a los desarrolladores (he visto qu uno de ustedes habla español)
pues di por casualidad con un articulo en la web en no recuerdo que sitio, que menciona este applet 
y me animo a redescubrir el entorno de escritorio cinamon en linux mint.

Sigan con el gran trabajo.

Ensegida dar algunas sugerencias:

1)Si fuera posible organizar en pestañas las diferentes configuraciones del menu, como son:
Tamaño, reaccion, categorias; etc.

2)Una configuracion del menu que deberia poder mantenerse sin cambios al cambiar el aspecto del menu deberia ser el texto y icono del mismo, ya que he notado que en LM17.1 se restauran estos dos valores cada que cambio el aspecto del menu y entonces tengo que cambiarlos nuevamente.

3) En cuanto a los menus Dragon y Helena podria sugerir aplicar transparencia, aunque claro; esta no se limitaria solo a estos menus.  

4)Si de menus con aspecto gnome/osx hablamos, sugeriria poder eliminar el texto de las categorias de aplicaciones y la posibilidad de que este se muestre debajo de la lista de aplicaciones.

5)Respecto al diseño sugeriria añadir un diseño windows XP, e incluso uno win2K.

Sin mas por el momento, esto seria todo mi comentario ya que aun estoy redescubriendo cinnamon
gracias a este muy acertado applet. Ademas de ser nuevo aqui en github.

**Comment by lestcape** [comment]
Hola, gracias por tus sugerencias. Soy cubano, pero estudio mi doctorado en Cuernavaca Morelos.

Que bueno que te has decidido a crearte una cuenta en github y ayudarnos a hacer las cosas mejores. Sin ayuda, pues no hay nada.

Respondiendo a tus interrogantes. No se como andas en ingles, porque las referencias que puedo darte son en ingles, pero bueno... Acá te va la explicación y las referencias.

1- Lo que se puede hacer es crear un nuevo programa de configuración o incluir tu solicitud a la mía en Cinnamon, o que me ayudes con el programa que estoy haciendo para que salga más rápido y mejor, pues una de las cosas que planeo incluir es eso mismo que estas pidiendo.

Que ocurre en la actualidad:

Los applet desklet y extensiones tienen un ficherito dentro que se llama settings-schema.json dicho archivo contiene una lista de artefactos gráficos con sus valores predeterminados, texto a mostrar, etc.... Estos artefactos gráficos, no pueden ser cualquier artefacto, solo los que Cinnamon-Settings soporta y deben de ir escritos en la forma en que Cinnamon-Settings los puede leer, de otra forma no podrían cargarse. Sin embargo, no hay forma de decirle a Cinnamon-Settings en que orden o manera debe de mostrar estos artefactos(al menos no todavía). Es por eso que queda fuera de mi control, el como presentar los datos. Más que eso, yo solo puedo esperar a que Cinnamon-Settings me de los datos que el quiera darme. Por ahora solo me da por cada artefacto un dato, el más importante de todos. Por ejemplo si estas configurando un color, el color seleccionado... Entonces no hay manera de decirle a Cinnamon-Settings, por ejemplo, que en determinado momento esconda(no muestre), determinados artefactos que no son de un tipo de menu (pero que si lo son de otros). Por lo que se muestran todos, sean válidos o no para la configuración actual del menú.

Referencia de la solicitud de incorporar paneles al settings de cinnamon, para que puedanser mostrados los datos de una manera ordenada(podría ser con pestañas):
https://github.com/linuxmint/Cinnamon/issues/2837

Referencia al programa que estoy haciendo para permitir esto y más cosas:
https://github.com/lestcape/Cinnamon-Installer

2- Podría ser lo que dices, pero me parece que estos datos son salvados independientemente. Tendría que verificarlo, de todas formas Configurable Menu usa Cinnamon-Installer (el programa que estoy haciendo, o mejor dicho, mejorando, para que haga mas cosas que antes hacia solo cinnamon settings), por lo que los nuevos cambios van a depender de como quede cinnamon installer. No tiene mucho sentido crear dos versiones del menú independientes, así que hay que esperar.

3- Cinnamon no tiene un lugar donde el usuario pueda configurar aspectos del tema. La transparencia es en realidad muy problemática y yo hago cosas de este estilo en Sticky Notes:
https://github.com/lestcape/Sticky-Notes

Pero no funciona cuando los fondos son escritos en base a una imagen y no a un color. Incluir esto en Configurable Menu no tiene mucho sentido, no podría solucionarse del todo y quedaría una transparencia diferente de la global del tema, cosa que yo considero no debe de ocurrir en el menú, el menú debe de integrase al tema perfectamente. De todas maneras, existe la posibilidad de cambiar este valor pero desde el archivo de configuración del tema, si incluyes los modificadores particulares de Configurable Menu: 
https://github.com/lestcape/Configurable-Menu/wiki/Add-Theme-Support

La mayoría de los autores de temas no lo incluyen y es por esto que a duras penas el menú puede usar los modificadores del menú estándar de canela que ciertamente es uno solo, luego no se podría variar esto en dependencia del menú seleccionado, a no ser que se incluyan los modificadores de Configurable Menu en el tema que estas usando.

4- Tendría que incluir una imagen por defecto para la categoría "todas las aplicaciones" que por ahora no tiene ninguna, pero eso es posible hacerlo, solo requiere de tiempo. El asunto es que no tiene sentido poner mas cosas a configurar, si ya de hecho la configuración es un desastre toda loca y desordenada (culpa de cinnamon-settings).

5- Eso es problemático (pero me lo han pedido bastantes personas), puesto que cinnamon no permite abrir simultáneamente varios menús a la vez. Configurable Menu no usa el código de cinnamon y burla esta restricción, para poder mostrar un menú con un sub-menú abiertos simultáneamente en algunos temas, pero solo para casos particulares controlables. Hacer un API general para esto es crear incompatibilidades futuras con el código de cinnamon, con la respectiva posibilidad de que el menú deje de funcionar producto de cualquier cambio en cinnamon, algo que seguro nadie quiere que pase. Entonces, lo correcto realmente es solicitar sea incluida una opción oficial que haga esto en el api de cinnamon, para que los desarrolladores tengan en cuenta esta api cuando hagan un cambio y no generen problemas a los que intentan mostrar varios menús simultáneamente.

Saludos.

**Comment by lestcape** [comment]
Después de verificar lo que has dicho en 2, puedo decirte que al menos para mi está funcionando. Creo que no conoces que en Cinnamon-Settings de Configurable Menu debes de dar click en la opción "Salvar la configuración del diseño actual", si pretendes que los datos modificados se salven. De otra forma, cuando cambies de diseño y regreses a donde estabas, se mostraran los datos por defecto de la configuración (es decir la imagen de Mint). Si salvaste se mostraran los datos tal cual los salvaste (es decir la imagen que seleccionaste).
