### ISSUE TITLE
Titles of menu items replace by numbers

### ISSUE THREAD

**Issue by jarspoon** [lestcape/Configurable-Menu#73]
Hi Lestcape,
Thanks for making this excellent applet. It does everything I need and more.
I am seeing something strange though: I'm using Windows 7 layout and occasionally the names of System Settings and Terminal are replaced by numbers - see attached image. I think it is the same programs but not always the same numbers. I can restore the names with right-click restore-default-name but it is weird. I have seen the same behaviour on two different machines both running Mint 17.1.
Thanks!
![screenshot from 2015-02-07 20_40_05](https://cloud.githubusercontent.com/assets/10901607/6094212/44e01702-af18-11e4-8a79-42e0a4fe385f.jpg)

**Comment by lestcape** [comment]
Yes thanks, something occurs with the ability to change the appname. This feature is broken, and need to be reimplemented. 

To restore the menu, open the configuration file:
~/.cinnamon/configs/configurableMenu@lestcape/configurableMenu@lestcape.json on gedit. Go to  "list-apps-names" and delete all values, then save and restart cinnamon. This  is how is by default:
```
"list-apps-names": {
        "type": "generic",
        "default": "",
        "value": ""
    },
```
another option is delete the folder ~/.cinnamon/configs/configurableMenu@lestcape/ and restart cinnamon, but on this case this will reset all menu configuration.

I will fix the problem...

Again thanks.

**Comment by sergioad** [comment]
Also another option is right click and them use restore default names, I had this same problem with the Mint layout, specially when my PC is powered off by hard shutdown, it is another way to solve it

**Comment by lestcape** [comment]
I think is fixed now here: https://github.com/lestcape/Configurable-Menu/archive/master.zip

**Comment by sergioad** [comment]
:+1:

**Comment by jarspoon** [comment]
Thanks very much for sorting this. Haven't seen the problem again since installing the fixed version. :+1:
