### ISSUE TITLE
Can't Change App Icons

### ISSUE THREAD

**Issue by fullmoonguru** [lestcape/Configurable-Menu#74]
Hi, thanks for a great applet!

I have changed the icons for LibreOffice but it still shows the old ones in the menu.  Even after going into menu editor and making sure they're the right ones.  And the hover icon does change.  It's just teh menu icons that are the old ones.  I'm assuming they are cached somewhere that I need to delete?

**Comment by lestcape** [comment]
I think that what you need is:
1- Restart cinnamon.
2- If icons not changed, please test what happens with the cinnamon menu...

If cinnamon menu is ok, please report me what icons you use to see this behavior...
If not, please verify that this theme really provide apps icons and then open an issue on the cinnamon developments page...

Thanks for the report.
Regards.

**Comment by fullmoonguru** [comment]
Yeah, same on the cinnamon menu.  I'll pursue it there. 

Thx-
