### ISSUE TITLE
Configurable menu stopped working after latest Cinnamon update

### ISSUE THREAD

**Issue by Garibaldo** [lestcape/Configurable-Menu#75]
After the latest Cinnamon update on github (which implemented the taskbar-on-multiple-monitor feature), the configurable menu applet doesn't work anymore.

**Comment by lestcape** [comment]
https://github.com/lestcape/Configurable-Menu/commit/77a532c6bf813f67dbd3706f5b319908379cde7a

**Comment by Garibaldo** [comment]
Thanks. It's working fine now.
