### ISSUE TITLE
Customize menu icon (the applet icon)

### ISSUE THREAD

**Issue by kminh** [lestcape/Configurable-Menu#77]
Hello, thanks for this nice applet.

Is there a way to customize the applet icon's size on the panel? Right now I'm allowing the panel to scale text/icon and while other icons are scaled at 0.64, this applet's icon seems to be scaled at 1, which makes it way too big.

Thank you.

**Comment by lestcape** [comment]
Hi, mm... I need to see what happens. what cinnamon version you have? With the change on the panel, this could happen... I handle this by my own, so a change on cinnamon need to be apply to the applet.
Thanks.

**Comment by kminh** [comment]
I'm using 2.4.8 and latest version of your applet. I imagine we need to add the icon scale factor into the applet, similar to the system tray applet. 

Thanks.

**Comment by lestcape** [comment]
Is added, just not with the new panel implementation... I need to update the applet, I know that now is not faster as before and there are several problems, but i'm working on several things at the same time. Anyway thanks.

**Comment by lestcape** [comment]
I really don't know what you do, but the systray icons and the applet icon are different things... When you try to compare, please compare the icon size with the cinnamon menu icon, not with the systray icons...
There is not difficult add a settings to change the icon size (or the scale), but really the menu have a lot of configurations and this create a problem on the communication between the applet and the cinnamon settings. I proposed a patch to increase the speed (https://github.com/linuxmint/Cinnamon/pull/3368), of this feature on cinnamon and not was merged. I don't know the reason, but this rejected joined with more thing was the original reason to increase the potential of cinnamon installer( https://github.com/lestcape/Cinnamon-Installer). I can not continue adding options in this situation.

Sorry.

**Comment by kminh** [comment]
Thanks for the follow up. Don't worry about it now.
