### ISSUE TITLE
Non-local Search Features Not Working Anymore

### ISSUE THREAD

**Issue by gritty-gitty** [lestcape/Configurable-Menu#78]
With *Configurable Menu* v1.7Beta (on *Cinnamon* v2.4.8+rebecca), the external search features like Wikipedia or the Internet search engines don’t show up in the menu anymore, although they’re still present — and activated, of course ;-) — in the configuration.

**Comment by lestcape** [comment]
Thats is because i don't use all settings of configurable menu, because is impossible. So, if there are a problem and nobody reported it to me, the problem continues for the eternity, because i only do this for users,  this not produce any benefits to me, just the opposite.

**Comment by lestcape** [comment]
Is fixed... https://github.com/lestcape/Configurable-Menu/commit/c2f73f9e98834cdd23bf851832fe0e9f9d9bd42c

**Comment by gritty-gitty** [comment]
With https://github.com/lestcape/Configurable-Menu/commit/c2f73f9e98834cdd23bf851832fe0e9f9d9bd42c it works again. Thanks a lot, it’s my favorite feature :-)

**Comment by lestcape** [comment]
Not matter.. you know... If you find something tell me...
