### ISSUE TITLE
Suspend and Hibernate keys are gone !!

### ISSUE THREAD

**Issue by MauiTux** [lestcape/Configurable-Menu#80]
Hi !
After a change of appearence in config menu, Suspend and Hibernate keys completely disappeared. No way to get them back from any config parameter.  Only "Logout, Screen Locker and, ,Shutdown" keys are now available.

Please help !   Mark

**Comment by lestcape** [comment]
Hi, what? When i use Suspend or Hibernate in my code. I just call to the standar system dialogs. I can not resolve this problem. Sorry.

**Comment by MauiTux** [comment]
Hi!  I changed to the DRAGON menu style and it turned back, unexplicably.
Thanks ;)

**Comment by lestcape** [comment]
That's, good. Seriously that is strange...

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
