### ISSUE TITLE
[Feature Request] Metro Style

### ISSUE THREAD

**Issue by DarkCerberus** [lestcape/Configurable-Menu#81]
Hello, 

Would it be possible to include this http://gnome-look.org/content/show.php/Wannabe+9?content=169020 style in the Configurable Menu applet - I really appreciate your work and some of us who like MS Windows or the Metro taskbar style would surely appreciate this being added.

**Comment by lestcape** [comment]
Hi. I have no intention of do this for now and for a long time. Is better don't say not, because maybe in a long next future i wanna to do it. This involved lost a lot of performances, and will require change the menu structure, generate a new keyboard navigation and more, is like make a new menu, that also i hate.
Sorry...

**Comment by gritty-gitty** [comment]
@lestcape: In other words, this menu alone would make *Configurable-Menu* possibly worse. Which seems to confirm my private opinion that *Cinnamon’s* menu doesn’t need to look nor to work like *Windows’* under *Metro* ;-)

**Comment by bluedxca93** [comment]
hi,
you could install a non cinnamon dock to act like a charms bar with a start menu button pointing to gnomenu. but its not easy to set up and its not cinnamon related at all. i discourage you from doing it until you know what you do.

**Comment by lestcape** [comment]
@bluedxca93 Yes, this is possible, also for the original Mint-Menu and all menu that can be handled externally, without depend of the internal structure. https://github.com/linuxmint/Cinnamon/issues/3773

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
