### ISSUE TITLE
Possible Configurable Menu Crash With Windows 7 Menu

### ISSUE THREAD

**Issue by Kayomn** [lestcape/Configurable-Menu#85]
This is a potential bug that I discovered moments ago.

Essentially when using the Windows 7 menu layout and you rearrange more than one item at once in the favourites panel of the menu it freezes the entire Cinnamon desktop environment.

I attempted to recover the cinnamon shell by entering tty1 and replacing cinnamon, however it only on-occasion works. Another thing I've noticed is that all system tray applications acquire a black box around them, however as far as I can tell this is just Cinnamon bricking itself.

System information:
OS: Ubuntu 14.04 trusty
Kernel: x86_64 Linux 3.19.0-32-generic
Uptime: 4m
Packages: 1690
Shell: bash 4.3.11
Resolution: 1366x768
DE: Cinnamon 2.6.12
WM: Muffin
CPU: AMD A6-3420M APU with Radeon HD Graphics @ 1.5GHz
GPU: Gallium 0.4 on AMD SUMO
RAM: 5444MiB

I've tested this bug three times now and as far as I can tell it is 100% repeatable, or at least on my laptop. When I get a chance I will also test this on another machine.

If you require any more information that you think will help fixing this issue please don't hesitate to ask.

**Comment by lestcape** [comment]
True.

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
