### ISSUE TITLE
[SUGGESTION] Update the kickoff menu style to the plasma 5's kickoff

### ISSUE THREAD

**Issue by sergioad** [lestcape/Configurable-Menu#90]
Hello @lestcape why do you not update the configurable menu's kickoff style to the plasma 5 kickoff?

**Comment by lestcape** [comment]
:) because Configurable Menu is not working properly now and i have not time, but could be, i need to see how kickoff is working.

**Comment by sergioad** [comment]
I understand, please advice me when you get configurabe menu working again in Cinnamon 2.8 please :smile:

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
