### ISSUE TITLE
Code errors. posy undefined, menuItem.menu undefined

### ISSUE THREAD

**Issue by t3pleni9** [lestcape/Configurable-Menu#91]
Hi, 
I faced the above two issues while launching and using the applet. Please find attached the patch file for the bug fix. 
[configMenu.txt](https://github.com/lestcape/Configurable-Menu/files/149843/configMenu.txt)

**Comment by lestcape** [comment]
Thanks, Configurable Menu is not usable really as in the middle of a migration and there are a lot of things that need to be fixed/changed... Any way i will take it in account.

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
