### ISSUE TITLE
[Feature Request] Layout similar to stylized or vampire but with system buttons next to search

### ISSUE THREAD

**Issue by xoger** [lestcape/Configurable-Menu#92]
Personally I don't need the information panel in stylized so it would be a better use of space if I had search next to the horizontal system buttons at either the top or the bottom.

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
