### ISSUE TITLE
[Feature Request] Allow multiple instances

### ISSUE THREAD

**Issue by xoger** [lestcape/Configurable-Menu#93]
On my duel screen setup I’m having to use this menu on my main monitor and the standard menu on my secondary monitor. The standard menu allows for multiple instances so I guess its possible for this if this is a fork.

**Comment by NikoKrause** [comment]
@xoger:
Add the following line to the metadata.json file of the applet: ` "max-instances": -1 `

**Comment by xoger** [comment]
oh well thats pretty simple, should be like that as standard if it doesn't create any issues

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
