### ISSUE TITLE
Where is the .css file to control menu trnasparency?

### ISSUE THREAD

**Issue by ven-u** [lestcape/Configurable-Menu#95]
I don't like transparency at all. In regular cinnamon, I always change the cinnamon.css file to remove transparency. Where is the .css file for configurable menu, so I can set them to ,1.0); intead of 0.9);

**Comment by lestcape** [comment]
As you can see, the menu use the current theme. If you change the theme, the menu also change his colors and transparencies. I really don' t remember what box i use exactly, but it's not create by me.
