### ISSUE TITLE
menu position incorrect and right click menu not working

### ISSUE THREAD

**Issue by piotrekkr** [lestcape/Configurable-Menu#96]
Hi,

I just installed your applet and it keeps sticking to left top corner of my desktop. It doesn't not change position even when I place applet on other side of screen or even when I move panel  to the top.  Also when I right click on aplet menu appears on same place as menu, and I can't click any of its items.

Screenshots
![screenshot from 2017-01-05 21-47-34](https://cloud.githubusercontent.com/assets/503782/21697142/564fb76e-d391-11e6-930d-635a545da487.png)
![screenshot from 2017-01-05 21-48-11](https://cloud.githubusercontent.com/assets/503782/21697143/5656bbe0-d391-11e6-8975-0c1e23aacf78.png)

I have Cinnamon 3.2.7

How can I fix this?

**Comment by lestcape** [comment]
What version you use? The spice version it's broken... I can not reproduce the problem in cinnamon 3.2.7
https://github.com/lestcape/Configurable-Menu/archive/master.zip

**Comment by piotrekkr** [comment]
Ok I installed newest version and it started to work. I recently upgraded linux mint to 18.1 and it seems that they have some older version in spices. Thank you for help.
